version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run:
          name: Install Debian dependencies
          command: |
            sudo apt-get update
            sudo apt-get install clang
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ./getcppdeps.sh
      - run: yarn test