version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10
  java:
    docker:
      - image: circleci/openjdk:11.0-jdk
  net:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

jobs:
  test-ts:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: yarn test

  test-cpp:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Debian dependencies
          command: |
            sudo apt-get update
            sudo apt-get install clang
      - run: ./script/getcppdeps.sh
      - run:
          name: Run tests 
          command: |
            clang++ -std=c++14 -Wall -Wfloat-conversion -Wmissing-declarations -g -o ./testcpp -Isrc/cpp/include src/cpp/packedrtree.cpp src/cpp/test/run_tests.cpp
            ./testcpp -d yes

  test-java:
    executor: java
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/java/pom.xml" }}
            - v1-dependencies-
      - run: cd src/java && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "src/java/pom.xml" }}
      - run: cd src/java && mvn test

  test-java:
    executor: net
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/net/FlatGeobuf/FlatGeobuf.csproj" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.nuget/packages
          key: v1-dependencies-{{ checksum "src/net/FlatGeobuf/FlatGeobuf.csproj" }}
      - run: cd src/net && dotnet test

workflows:
  main:
    jobs:
      - test-ts
      - test-cpp
      - test-java
      - test-net